/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Value = IDL.Rec();
export const TokenId = IDL.Nat;
export const Time = IDL.Int;
export const TransactionEvent = IDL.Record({
  'to' : IDL.Principal,
  'from' : IDL.Opt(IDL.Principal),
  'timestamp' : IDL.Int,
  'eventType' : IDL.Variant({ 'Mint' : IDL.Null, 'Transfer' : IDL.Null }),
});
export const NFTMetadata = IDL.Record({
  'tokenId' : TokenId,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'history' : IDL.Vec(TransactionEvent),
  'image' : IDL.Vec(IDL.Nat8),
  'isPublic' : IDL.Bool,
  'collectionName' : IDL.Opt(IDL.Text),
});
export const NFTPage = IDL.Record({
  'total' : IDL.Nat,
  'items' : IDL.Vec(NFTMetadata),
});
export const CollectionPhase = IDL.Variant({
  'Premium' : IDL.Null,
  'Free' : IDL.Null,
  'Bonus' : IDL.Null,
});
export const CycleHealth = IDL.Variant({
  'red' : IDL.Null,
  'orange' : IDL.Null,
  'green' : IDL.Null,
});
export const HealthStatus = IDL.Record({
  'status' : IDL.Text,
  'daysPercentage' : IDL.Nat,
  'imagesRemaining' : IDL.Nat,
  'estimatedStorageMB' : IDL.Nat,
  'healthColor' : CycleHealth,
  'rawCycles' : IDL.Nat,
  'daysRemaining' : IDL.Nat,
});
export const Standard = IDL.Record({ 'url' : IDL.Text, 'name' : IDL.Text });
export const Account = IDL.Record({
  'owner' : IDL.Principal,
  'subaccount' : IDL.Opt(IDL.Vec(IDL.Nat8)),
});
Value.fill(
  IDL.Variant({
    'Int' : IDL.Int,
    'Map' : IDL.Vec(IDL.Tuple(IDL.Text, Value)),
    'Nat' : IDL.Nat,
    'Blob' : IDL.Vec(IDL.Nat8),
    'Bool' : IDL.Bool,
    'Text' : IDL.Text,
    'Array' : IDL.Vec(IDL.Tuple(IDL.Text, Value)),
  })
);
export const MintResult = IDL.Variant({
  'ok' : TokenId,
  'err' : IDL.Text,
  'paymentRequired' : IDL.Null,
});
export const VisibilityResult = IDL.Variant({
  'ok' : IDL.Null,
  'err' : IDL.Text,
});
export const TopUpResult = IDL.Variant({
  'ok' : IDL.Record({
    'platformFee' : IDL.Nat64,
    'icpUsed' : IDL.Nat64,
    'cyclesMinted' : IDL.Nat,
  }),
  'err' : IDL.Text,
});
export const TransferResult = IDL.Variant({
  'ok' : IDL.Null,
  'err' : IDL.Text,
});
export const WithdrawResult = IDL.Variant({
  'ok' : IDL.Nat64,
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  'createMyCollection' : IDL.Func([], [IDL.Principal], []),
  'estimateCycles' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'estimateICPForImages' : IDL.Func(
      [IDL.Nat, IDL.Float64],
      [IDL.Float64],
      ['query'],
    ),
  'estimateImagesForICP' : IDL.Func(
      [IDL.Float64, IDL.Float64],
      [IDL.Nat],
      ['query'],
    ),
  'getAdminPrincipal' : IDL.Func([], [IDL.Principal], ['query']),
  'getAllPublicNFTs' : IDL.Func([], [IDL.Vec(NFTMetadata)], ['query']),
  'getAllPublicNFTsByOwner' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(NFTMetadata)],
      ['query'],
    ),
  'getAllPublicNFTsPaginated' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [NFTPage],
      ['query'],
    ),
  'getCollectionPhase' : IDL.Func([IDL.Principal], [CollectionPhase], []),
  'getFactoryAccountId' : IDL.Func([], [IDL.Text], ['query']),
  'getICPPrice' : IDL.Func([], [IDL.Float64], []),
  'getMyCollection' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IDL.Principal)],
      ['query'],
    ),
  'getMyCollectionCycles' : IDL.Func([], [IDL.Nat], []),
  'getMyHealthStatus' : IDL.Func([], [HealthStatus], []),
  'getMyMintCount' : IDL.Func([IDL.Principal], [IDL.Nat], []),
  'getMyNFTs' : IDL.Func([], [IDL.Vec(NFTMetadata)], []),
  'getMyNFTsPaginated' : IDL.Func([IDL.Nat, IDL.Nat], [NFTPage], []),
  'getNFT' : IDL.Func([TokenId], [IDL.Opt(NFTMetadata)], ['query']),
  'getNFTHistory' : IDL.Func(
      [TokenId],
      [IDL.Opt(IDL.Vec(TransactionEvent))],
      ['query'],
    ),
  'getPlatformFees' : IDL.Func([], [IDL.Nat64], ['query']),
  'icrc10_supported_standards' : IDL.Func([], [IDL.Vec(Standard)], ['query']),
  'icrc7_description' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'icrc7_name' : IDL.Func([], [IDL.Text], ['query']),
  'icrc7_owner_of' : IDL.Func([IDL.Nat], [IDL.Opt(Account)], ['query']),
  'icrc7_symbol' : IDL.Func([], [IDL.Text], ['query']),
  'icrc7_token_metadata' : IDL.Func(
      [IDL.Vec(IDL.Nat)],
      [IDL.Vec(IDL.Opt(IDL.Vec(IDL.Tuple(IDL.Text, Value))))],
      ['query'],
    ),
  'icrc7_tokens' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Nat)],
      ['query'],
    ),
  'icrc7_tokens_of' : IDL.Func(
      [Account, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Nat)],
      ['query'],
    ),
  'icrc7_total_supply' : IDL.Func([], [IDL.Nat], ['query']),
  'initSelf' : IDL.Func([], [], []),
  'mintNFT' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Nat8),
        IDL.Opt(IDL.Principal),
        IDL.Bool,
        IDL.Opt(IDL.Text),
      ],
      [MintResult],
      [],
    ),
  'setNFTVisibility' : IDL.Func([TokenId, IDL.Bool], [VisibilityResult], []),
  'topUpCollection' : IDL.Func([IDL.Nat64], [TopUpResult], []),
  'transferNFT' : IDL.Func([TokenId, IDL.Principal], [TransferResult], []),
  'withdrawPlatformFees' : IDL.Func([IDL.Principal], [WithdrawResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Value = IDL.Rec();
  const TokenId = IDL.Nat;
  const Time = IDL.Int;
  const TransactionEvent = IDL.Record({
    'to' : IDL.Principal,
    'from' : IDL.Opt(IDL.Principal),
    'timestamp' : IDL.Int,
    'eventType' : IDL.Variant({ 'Mint' : IDL.Null, 'Transfer' : IDL.Null }),
  });
  const NFTMetadata = IDL.Record({
    'tokenId' : TokenId,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'history' : IDL.Vec(TransactionEvent),
    'image' : IDL.Vec(IDL.Nat8),
    'isPublic' : IDL.Bool,
    'collectionName' : IDL.Opt(IDL.Text),
  });
  const NFTPage = IDL.Record({
    'total' : IDL.Nat,
    'items' : IDL.Vec(NFTMetadata),
  });
  const CollectionPhase = IDL.Variant({
    'Premium' : IDL.Null,
    'Free' : IDL.Null,
    'Bonus' : IDL.Null,
  });
  const CycleHealth = IDL.Variant({
    'red' : IDL.Null,
    'orange' : IDL.Null,
    'green' : IDL.Null,
  });
  const HealthStatus = IDL.Record({
    'status' : IDL.Text,
    'daysPercentage' : IDL.Nat,
    'imagesRemaining' : IDL.Nat,
    'estimatedStorageMB' : IDL.Nat,
    'healthColor' : CycleHealth,
    'rawCycles' : IDL.Nat,
    'daysRemaining' : IDL.Nat,
  });
  const Standard = IDL.Record({ 'url' : IDL.Text, 'name' : IDL.Text });
  const Account = IDL.Record({
    'owner' : IDL.Principal,
    'subaccount' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  });
  Value.fill(
    IDL.Variant({
      'Int' : IDL.Int,
      'Map' : IDL.Vec(IDL.Tuple(IDL.Text, Value)),
      'Nat' : IDL.Nat,
      'Blob' : IDL.Vec(IDL.Nat8),
      'Bool' : IDL.Bool,
      'Text' : IDL.Text,
      'Array' : IDL.Vec(IDL.Tuple(IDL.Text, Value)),
    })
  );
  const MintResult = IDL.Variant({
    'ok' : TokenId,
    'err' : IDL.Text,
    'paymentRequired' : IDL.Null,
  });
  const VisibilityResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const TopUpResult = IDL.Variant({
    'ok' : IDL.Record({
      'platformFee' : IDL.Nat64,
      'icpUsed' : IDL.Nat64,
      'cyclesMinted' : IDL.Nat,
    }),
    'err' : IDL.Text,
  });
  const TransferResult = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const WithdrawResult = IDL.Variant({ 'ok' : IDL.Nat64, 'err' : IDL.Text });
  
  return IDL.Service({
    'createMyCollection' : IDL.Func([], [IDL.Principal], []),
    'estimateCycles' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'estimateICPForImages' : IDL.Func(
        [IDL.Nat, IDL.Float64],
        [IDL.Float64],
        ['query'],
      ),
    'estimateImagesForICP' : IDL.Func(
        [IDL.Float64, IDL.Float64],
        [IDL.Nat],
        ['query'],
      ),
    'getAdminPrincipal' : IDL.Func([], [IDL.Principal], ['query']),
    'getAllPublicNFTs' : IDL.Func([], [IDL.Vec(NFTMetadata)], ['query']),
    'getAllPublicNFTsByOwner' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(NFTMetadata)],
        ['query'],
      ),
    'getAllPublicNFTsPaginated' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [NFTPage],
        ['query'],
      ),
    'getCollectionPhase' : IDL.Func([IDL.Principal], [CollectionPhase], []),
    'getFactoryAccountId' : IDL.Func([], [IDL.Text], ['query']),
    'getICPPrice' : IDL.Func([], [IDL.Float64], []),
    'getMyCollection' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Principal)],
        ['query'],
      ),
    'getMyCollectionCycles' : IDL.Func([], [IDL.Nat], []),
    'getMyHealthStatus' : IDL.Func([], [HealthStatus], []),
    'getMyMintCount' : IDL.Func([IDL.Principal], [IDL.Nat], []),
    'getMyNFTs' : IDL.Func([], [IDL.Vec(NFTMetadata)], []),
    'getMyNFTsPaginated' : IDL.Func([IDL.Nat, IDL.Nat], [NFTPage], []),
    'getNFT' : IDL.Func([TokenId], [IDL.Opt(NFTMetadata)], ['query']),
    'getNFTHistory' : IDL.Func(
        [TokenId],
        [IDL.Opt(IDL.Vec(TransactionEvent))],
        ['query'],
      ),
    'getPlatformFees' : IDL.Func([], [IDL.Nat64], ['query']),
    'icrc10_supported_standards' : IDL.Func([], [IDL.Vec(Standard)], ['query']),
    'icrc7_description' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'icrc7_name' : IDL.Func([], [IDL.Text], ['query']),
    'icrc7_owner_of' : IDL.Func([IDL.Nat], [IDL.Opt(Account)], ['query']),
    'icrc7_symbol' : IDL.Func([], [IDL.Text], ['query']),
    'icrc7_token_metadata' : IDL.Func(
        [IDL.Vec(IDL.Nat)],
        [IDL.Vec(IDL.Opt(IDL.Vec(IDL.Tuple(IDL.Text, Value))))],
        ['query'],
      ),
    'icrc7_tokens' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Nat)],
        ['query'],
      ),
    'icrc7_tokens_of' : IDL.Func(
        [Account, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Nat)],
        ['query'],
      ),
    'icrc7_total_supply' : IDL.Func([], [IDL.Nat], ['query']),
    'initSelf' : IDL.Func([], [], []),
    'mintNFT' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Nat8),
          IDL.Opt(IDL.Principal),
          IDL.Bool,
          IDL.Opt(IDL.Text),
        ],
        [MintResult],
        [],
      ),
    'setNFTVisibility' : IDL.Func([TokenId, IDL.Bool], [VisibilityResult], []),
    'topUpCollection' : IDL.Func([IDL.Nat64], [TopUpResult], []),
    'transferNFT' : IDL.Func([TokenId, IDL.Principal], [TransferResult], []),
    'withdrawPlatformFees' : IDL.Func([IDL.Principal], [WithdrawResult], []),
  });
};

export const init = ({ IDL }) => { return []; };