/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Account {
  'owner' : Principal,
  'subaccount' : [] | [Uint8Array],
}
export type CollectionPhase = { 'Premium' : null } |
  { 'Free' : null } |
  { 'Bonus' : null };
export type CycleHealth = { 'red' : null } |
  { 'orange' : null } |
  { 'green' : null };
export interface HealthStatus {
  'status' : string,
  'daysPercentage' : bigint,
  'imagesRemaining' : bigint,
  'estimatedStorageMB' : bigint,
  'healthColor' : CycleHealth,
  'rawCycles' : bigint,
  'daysRemaining' : bigint,
}
export type MintResult = { 'ok' : TokenId } |
  { 'err' : string } |
  { 'paymentRequired' : null };
export interface NFTMetadata {
  'tokenId' : TokenId,
  'owner' : Principal,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'history' : Array<TransactionEvent>,
  'image' : Uint8Array,
  'isPublic' : boolean,
  'collectionName' : [] | [string],
}
export interface NFTPage { 'total' : bigint, 'items' : Array<NFTMetadata> }
export interface Standard { 'url' : string, 'name' : string }
export type Time = bigint;
export type TokenId = bigint;
export type TopUpResult = {
    'ok' : {
      'platformFee' : bigint,
      'icpUsed' : bigint,
      'cyclesMinted' : bigint,
    }
  } |
  { 'err' : string };
export interface TransactionEvent {
  'to' : Principal,
  'from' : [] | [Principal],
  'timestamp' : bigint,
  'eventType' : { 'Mint' : null } |
    { 'Transfer' : null },
}
export type TransferResult = { 'ok' : null } |
  { 'err' : string };
export type Value = { 'Int' : bigint } |
  { 'Map' : Array<[string, Value]> } |
  { 'Nat' : bigint } |
  { 'Blob' : Uint8Array } |
  { 'Bool' : boolean } |
  { 'Text' : string } |
  { 'Array' : Array<[string, Value]> };
export type VisibilityResult = { 'ok' : null } |
  { 'err' : string };
export type WithdrawResult = { 'ok' : bigint } |
  { 'err' : string };
export interface _SERVICE {
  'createMyCollection' : ActorMethod<[], Principal>,
  'estimateCycles' : ActorMethod<[bigint], bigint>,
  'estimateICPForImages' : ActorMethod<[bigint, number], number>,
  'estimateImagesForICP' : ActorMethod<[number, number], bigint>,
  'getAdminPrincipal' : ActorMethod<[], Principal>,
  'getAllPublicNFTs' : ActorMethod<[], Array<NFTMetadata>>,
  'getAllPublicNFTsByOwner' : ActorMethod<[Principal], Array<NFTMetadata>>,
  'getAllPublicNFTsPaginated' : ActorMethod<[bigint, bigint], NFTPage>,
  'getCollectionPhase' : ActorMethod<[Principal], CollectionPhase>,
  'getFactoryAccountId' : ActorMethod<[], string>,
  'getICPPrice' : ActorMethod<[], number>,
  'getMyCollection' : ActorMethod<[Principal], [] | [Principal]>,
  'getMyCollectionCycles' : ActorMethod<[], bigint>,
  'getMyHealthStatus' : ActorMethod<[], HealthStatus>,
  'getMyMintCount' : ActorMethod<[Principal], bigint>,
  /**
   * / One-time init — call once after deploy to wire self-principal.
   */
  'getMyNFTs' : ActorMethod<[], Array<NFTMetadata>>,
  'getMyNFTsPaginated' : ActorMethod<[bigint, bigint], NFTPage>,
  'getNFT' : ActorMethod<[TokenId], [] | [NFTMetadata]>,
  'getNFTHistory' : ActorMethod<[TokenId], [] | [Array<TransactionEvent>]>,
  'getPlatformFees' : ActorMethod<[], bigint>,
  'icrc10_supported_standards' : ActorMethod<[], Array<Standard>>,
  'icrc7_description' : ActorMethod<[], [] | [string]>,
  'icrc7_name' : ActorMethod<[], string>,
  'icrc7_owner_of' : ActorMethod<[bigint], [] | [Account]>,
  'icrc7_symbol' : ActorMethod<[], string>,
  'icrc7_token_metadata' : ActorMethod<
    [Array<bigint>],
    Array<[] | [Array<[string, Value]>]>
  >,
  'icrc7_tokens' : ActorMethod<[[] | [bigint], [] | [bigint]], Array<bigint>>,
  'icrc7_tokens_of' : ActorMethod<
    [Account, [] | [bigint], [] | [bigint]],
    Array<bigint>
  >,
  'icrc7_total_supply' : ActorMethod<[], bigint>,
  /**
   * / One-time init — call once after deploy to wire self-principal.
   */
  'initSelf' : ActorMethod<[], undefined>,
  'mintNFT' : ActorMethod<
    [string, string, Uint8Array, [] | [Principal], boolean, [] | [string]],
    MintResult
  >,
  'setNFTVisibility' : ActorMethod<[TokenId, boolean], VisibilityResult>,
  'topUpCollection' : ActorMethod<[bigint], TopUpResult>,
  'transferNFT' : ActorMethod<[TokenId, Principal], TransferResult>,
  'withdrawPlatformFees' : ActorMethod<[Principal], WithdrawResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];