/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Account {
  'owner' : Principal,
  'subaccount' : [] | [Uint8Array],
}
export type CollectionPhase = { 'Premium' : null } |
  { 'Free' : null } |
  { 'Bonus' : null };
export type CycleHealth = { 'red' : null } |
  { 'orange' : null } |
  { 'green' : null };
export interface HealthStatus {
  'status' : string,
  'daysPercentage' : bigint,
  'imagesRemaining' : bigint,
  'estimatedStorageMB' : bigint,
  'healthColor' : CycleHealth,
  'rawCycles' : bigint,
  'daysRemaining' : bigint,
}
export type MintResult = { 'ok' : TokenId } |
  { 'err' : string } |
  { 'paymentRequired' : null };
export interface NFTMetadata {
  'tokenId' : TokenId,
  'owner' : Principal,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'history' : Array<TransactionEvent>,
  'image' : Uint8Array,
  'isPublic' : boolean,
  'collectionName' : [] | [string],
}
export interface NFTMetadataLite {
  'tokenId' : TokenId,
  'owner' : Principal,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'history' : Array<TransactionEvent>,
  'collectionCanisterId' : [] | [string],
  'isPublic' : boolean,
  'collectionName' : [] | [string],
}
export interface NFTPageLite {
  'total' : bigint,
  'items' : Array<NFTMetadataLite>,
}
export interface PendingTx {
  'status' : TxStatus,
  'lastAttemptAt' : bigint,
  'collectionId' : Principal,
  'createdAt' : bigint,
  'retryCount' : bigint,
  'blockIndex' : bigint,
  'caller' : Principal,
  'amount' : bigint,
}
export type ProcessTopUpResult = {
    'ok' : {
      'platformFee' : bigint,
      'icpUsed' : bigint,
      'cyclesMinted' : bigint,
    }
  } |
  { 'err' : string };
export interface Standard { 'url' : string, 'name' : string }
export type Time = bigint;
export type TokenId = bigint;
export type TopUpResult = {
    'ok' : {
      'platformFee' : bigint,
      'icpUsed' : bigint,
      'cyclesMinted' : bigint,
    }
  } |
  { 'err' : string };
export interface TransactionEvent {
  'to' : Principal,
  'from' : [] | [Principal],
  'timestamp' : bigint,
  'eventType' : { 'Mint' : null } |
    { 'Transfer' : null },
}
export type TransferResult = { 'ok' : null } |
  { 'err' : string };
export type TxStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'failed' : null };
export type Value = { 'Int' : bigint } |
  { 'Map' : Array<[string, Value]> } |
  { 'Nat' : bigint } |
  { 'Blob' : Uint8Array } |
  { 'Bool' : boolean } |
  { 'Text' : string } |
  { 'Array' : Array<[string, Value]> };
export type VisibilityResult = { 'ok' : null } |
  { 'err' : string };
export type WithdrawResult = { 'ok' : bigint } |
  { 'err' : string };
export interface _SERVICE {
  'addAdmin' : ActorMethod<[Principal], { 'ok' : null } | { 'err' : string }>,
  'adminRetryTopUp' : ActorMethod<[bigint], ProcessTopUpResult>,
  'cleanupCorruptedRegistry' : ActorMethod<[], bigint>,
  'createMyCollection' : ActorMethod<
    [],
    { 'ok' : Principal } |
      { 'err' : string }
  >,
  'estimateCycles' : ActorMethod<[bigint], bigint>,
  'estimateICPForImages' : ActorMethod<[bigint, number], number>,
  'estimateImagesForICP' : ActorMethod<[number, number], bigint>,
  'getAdminPrincipal' : ActorMethod<[], Principal>,
  'getAllPublicNFTs' : ActorMethod<[], Array<NFTMetadataLite>>,
  'getAllPublicNFTsByOwner' : ActorMethod<[Principal], Array<NFTMetadataLite>>,
  'getAllPublicNFTsPaginated' : ActorMethod<[bigint, bigint], NFTPageLite>,
  'getCmcDepositAddress' : ActorMethod<[], string>,
  'getCollectionPhase' : ActorMethod<[Principal], CollectionPhase>,
  'getCollectionStatus' : ActorMethod<
    [Principal],
    { 'ownerPrincipal' : Principal, 'imageCount' : bigint, 'cycles' : bigint }
  >,
  'getFactoryAccountId' : ActorMethod<[], string>,
  'getICPPrice' : ActorMethod<[], number>,
  'getMyCollection' : ActorMethod<[Principal], Array<Principal>>,
  'getMyCollectionCycles' : ActorMethod<[], bigint>,
  'getMyCollections' : ActorMethod<[Principal], Array<Principal>>,
  'getMyHealthStatus' : ActorMethod<[], HealthStatus>,
  'getMyMintCount' : ActorMethod<[Principal], bigint>,
  'getMyNFTs' : ActorMethod<[], Array<NFTMetadataLite>>,
  'getMyNFTsPaginated' : ActorMethod<[bigint, bigint], NFTPageLite>,
  'getMyPendingTransactions' : ActorMethod<[], Array<PendingTx>>,
  'getNFT' : ActorMethod<[TokenId], [] | [NFTMetadata]>,
  'getNFTHistory' : ActorMethod<[TokenId], [] | [Array<TransactionEvent>]>,
  'getNFTImage' : ActorMethod<[TokenId], [] | [Uint8Array]>,
  'getPendingTransactions' : ActorMethod<[], Array<PendingTx>>,
  'getPlatformFees' : ActorMethod<[], bigint>,
  'getStatus' : ActorMethod<
    [],
    {
      'memory' : bigint,
      'cycles' : bigint,
      'heap_memory' : bigint,
      'estimate_days' : bigint,
    }
  >,
  'getUserRegistryEntry' : ActorMethod<[], Array<Principal>>,
  'icrc10_supported_standards' : ActorMethod<[], Array<Standard>>,
  'icrc7_description' : ActorMethod<[], [] | [string]>,
  'icrc7_name' : ActorMethod<[], string>,
  'icrc7_owner_of' : ActorMethod<[bigint], [] | [Account]>,
  'icrc7_symbol' : ActorMethod<[], string>,
  'icrc7_token_metadata' : ActorMethod<
    [Array<bigint>],
    Array<[] | [Array<[string, Value]>]>
  >,
  'icrc7_tokens' : ActorMethod<[[] | [bigint], [] | [bigint]], Array<bigint>>,
  'icrc7_tokens_of' : ActorMethod<
    [Account, [] | [bigint], [] | [bigint]],
    Array<bigint>
  >,
  'icrc7_total_supply' : ActorMethod<[], bigint>,
  /**
   * / Manual trigger — available for emergency use via Candid UI / frontend.
   * / Also purges any corrupted aaaaa-aa registry entries left from failed createMyCollection calls.
   */
  'initSelf' : ActorMethod<[], undefined>,
  'isUsingDefaultCollection' : ActorMethod<[Principal], boolean>,
  'listAdmins' : ActorMethod<[], Array<Principal>>,
  'mintNFT' : ActorMethod<
    [string, string, Uint8Array, [] | [Principal], boolean, [] | [string]],
    MintResult
  >,
  'processTopUp' : ActorMethod<[bigint, Principal], ProcessTopUpResult>,
  'removeAdmin' : ActorMethod<
    [Principal],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'removeMyCollection' : ActorMethod<
    [Principal],
    { 'ok' : boolean } |
      { 'err' : string }
  >,
  'retryTopUp' : ActorMethod<[bigint], ProcessTopUpResult>,
  'setNFTVisibility' : ActorMethod<[TokenId, boolean], VisibilityResult>,
  'topUpCollection' : ActorMethod<[bigint], TopUpResult>,
  'transferNFT' : ActorMethod<[TokenId, Principal], TransferResult>,
  'withdrawPlatformFees' : ActorMethod<[Principal], WithdrawResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];