/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Account {
    owner: Principal;
    subaccount?: Uint8Array;
}
export type Time = bigint;
export type TokenId = bigint;
export type WithdrawResult = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
};
export type MintResult = {
    __kind__: "ok";
    ok: TokenId;
} | {
    __kind__: "err";
    err: string;
} | {
    __kind__: "paymentRequired";
    paymentRequired: null;
};
export interface HealthStatus {
    status: string;
    daysPercentage: bigint;
    imagesRemaining: bigint;
    estimatedStorageMB: bigint;
    healthColor: CycleHealth;
    rawCycles: bigint;
    daysRemaining: bigint;
}
export interface NFTMetadataLite {
    tokenId: TokenId;
    owner: Principal;
    name: string;
    createdAt: Time;
    description: string;
    history: Array<TransactionEvent>;
    isPublic: boolean;
    collectionName?: string;
}
export interface NFTPageLite {
    total: bigint;
    items: Array<NFTMetadataLite>;
}
export type TopUpResult = {
    __kind__: "ok";
    ok: {
        platformFee: bigint;
        icpUsed: bigint;
        cyclesMinted: bigint;
    };
} | {
    __kind__: "err";
    err: string;
};
export type ProcessTopUpResult = {
    __kind__: "ok";
    ok: {
        platformFee: bigint;
        icpUsed: bigint;
        cyclesMinted: bigint;
    };
} | {
    __kind__: "err";
    err: string;
};
export type TransferResult = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export interface TransactionEvent {
    to: Principal;
    from?: Principal;
    timestamp: bigint;
    eventType: Variant_Mint_Transfer;
}
export interface NFTMetadata {
    tokenId: TokenId;
    owner: Principal;
    name: string;
    createdAt: Time;
    description: string;
    history: Array<TransactionEvent>;
    image: Uint8Array;
    isPublic: boolean;
    collectionName?: string;
}
export type VisibilityResult = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export type Value = {
    __kind__: "Int";
    Int: bigint;
} | {
    __kind__: "Map";
    Map: Array<[string, Value]>;
} | {
    __kind__: "Nat";
    Nat: bigint;
} | {
    __kind__: "Blob";
    Blob: Uint8Array;
} | {
    __kind__: "Bool";
    Bool: boolean;
} | {
    __kind__: "Text";
    Text: string;
} | {
    __kind__: "Array";
    Array: Array<[string, Value]>;
};
export interface PendingTx {
    status: TxStatus;
    lastAttemptAt: bigint;
    collectionId: Principal;
    createdAt: bigint;
    retryCount: bigint;
    blockIndex: bigint;
    caller: Principal;
    amount: bigint;
}
export interface Standard {
    url: string;
    name: string;
}
export enum CollectionPhase {
    Premium = "Premium",
    Free = "Free",
    Bonus = "Bonus"
}
export enum CycleHealth {
    red = "red",
    orange = "orange",
    green = "green"
}
export enum TxStatus {
    pending = "pending",
    completed = "completed",
    failed = "failed"
}
export enum Variant_Mint_Transfer {
    Mint = "Mint",
    Transfer = "Transfer"
}
export interface backendInterface {
    addAdmin(newAdmin: Principal): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminRetryTopUp(blockIndex: bigint): Promise<ProcessTopUpResult>;
    cleanupCorruptedRegistry(): Promise<bigint>;
    createMyCollection(): Promise<Principal>;
    estimateCycles(imageCount: bigint): Promise<bigint>;
    estimateICPForImages(imageCount: bigint, icpPriceUSD: number): Promise<number>;
    estimateImagesForICP(icpAmount: number, icpPriceUSD: number): Promise<bigint>;
    getAdminPrincipal(): Promise<Principal>;
    getAllPublicNFTs(): Promise<Array<NFTMetadataLite>>;
    getAllPublicNFTsByOwner(owner: Principal): Promise<Array<NFTMetadataLite>>;
    getAllPublicNFTsPaginated(offset: bigint, limit: bigint): Promise<NFTPageLite>;
    getCmcDepositAddress(): Promise<string>;
    getCollectionPhase(user: Principal): Promise<CollectionPhase>;
    getCollectionStatus(collectionId: Principal): Promise<{
        ownerPrincipal: Principal;
        imageCount: bigint;
        cycles: bigint;
    }>;
    getFactoryAccountId(): Promise<string>;
    getICPPrice(): Promise<number>;
    getMyCollection(user: Principal): Promise<Principal | null>;
    getMyCollectionCycles(): Promise<bigint>;
    getMyHealthStatus(): Promise<HealthStatus>;
    getMyMintCount(user: Principal): Promise<bigint>;
    getMyNFTs(): Promise<Array<NFTMetadataLite>>;
    getMyNFTsPaginated(offset: bigint, limit: bigint): Promise<NFTPageLite>;
    getMyPendingTransactions(): Promise<Array<PendingTx>>;
    getNFT(tokenId: TokenId): Promise<NFTMetadata | null>;
    /**
     * / Manual trigger — available for emergency use via Candid UI / frontend.
     * / Also purges any corrupted aaaaa-aa registry entries left from failed createMyCollection calls.
     */
    getNFTHistory(tokenId: TokenId): Promise<Array<TransactionEvent> | null>;
    getNFTImage(tokenId: TokenId): Promise<Uint8Array | null>;
    getPendingTransactions(): Promise<Array<PendingTx>>;
    getPlatformFees(): Promise<bigint>;
    getStatus(): Promise<{
        memory: bigint;
        cycles: bigint;
        heap_memory: bigint;
        estimate_days: bigint;
    }>;
    getUserRegistryEntry(): Promise<Principal | null>;
    icrc10_supported_standards(): Promise<Array<Standard>>;
    icrc7_description(): Promise<string | null>;
    icrc7_name(): Promise<string>;
    icrc7_owner_of(tokenId: bigint): Promise<Account | null>;
    icrc7_symbol(): Promise<string>;
    icrc7_token_metadata(tokenIds: Array<bigint>): Promise<Array<Array<[string, Value]> | null>>;
    icrc7_tokens(prev: bigint | null, take: bigint | null): Promise<Array<bigint>>;
    icrc7_tokens_of(account: Account, prev: bigint | null, take: bigint | null): Promise<Array<bigint>>;
    icrc7_total_supply(): Promise<bigint>;
    /**
     * / Manual trigger — available for emergency use via Candid UI / frontend.
     * / Also purges any corrupted aaaaa-aa registry entries left from failed createMyCollection calls.
     */
    initSelf(): Promise<void>;
    isUsingDefaultCollection(user: Principal): Promise<boolean>;
    listAdmins(): Promise<Array<Principal>>;
    mintNFT(name: string, description: string, image: Uint8Array, recipientOpt: Principal | null, isPublic: boolean, collectionName: string | null): Promise<MintResult>;
    processTopUp(blockIndex: bigint, collectionId: Principal): Promise<ProcessTopUpResult>;
    removeAdmin(adminToRemove: Principal): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    retryTopUp(blockIndex: bigint): Promise<ProcessTopUpResult>;
    setNFTVisibility(tokenId: TokenId, isPublic: boolean): Promise<VisibilityResult>;
    topUpCollection(blockIndex: bigint): Promise<TopUpResult>;
    transferNFT(tokenId: TokenId, to: Principal): Promise<TransferResult>;
    withdrawPlatformFees(toPrincipal: Principal): Promise<WithdrawResult>;
}
import type { Account as _Account, CollectionPhase as _CollectionPhase, CycleHealth as _CycleHealth, HealthStatus as _HealthStatus, MintResult as _MintResult, NFTMetadata as _NFTMetadata, NFTMetadataLite as _NFTMetadataLite, NFTPageLite as _NFTPageLite, PendingTx as _PendingTx, ProcessTopUpResult as _ProcessTopUpResult, Time as _Time, TokenId as _TokenId, TopUpResult as _TopUpResult, TransactionEvent as _TransactionEvent, TransferResult as _TransferResult, TxStatus as _TxStatus, Value as _Value, VisibilityResult as _VisibilityResult, WithdrawResult as _WithdrawResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAdmin(arg0: Principal): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdmin(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdmin(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminRetryTopUp(arg0: bigint): Promise<ProcessTopUpResult> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRetryTopUp(arg0);
                return from_candid_ProcessTopUpResult_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRetryTopUp(arg0);
            return from_candid_ProcessTopUpResult_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async cleanupCorruptedRegistry(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.cleanupCorruptedRegistry();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cleanupCorruptedRegistry();
            return result;
        }
    }
    async createMyCollection(): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.createMyCollection();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMyCollection();
            return result;
        }
    }
    async estimateCycles(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.estimateCycles(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.estimateCycles(arg0);
            return result;
        }
    }
    async estimateICPForImages(arg0: bigint, arg1: number): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.estimateICPForImages(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.estimateICPForImages(arg0, arg1);
            return result;
        }
    }
    async estimateImagesForICP(arg0: number, arg1: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.estimateImagesForICP(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.estimateImagesForICP(arg0, arg1);
            return result;
        }
    }
    async getAdminPrincipal(): Promise<Principal> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminPrincipal();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminPrincipal();
            return result;
        }
    }
    async getAllPublicNFTs(): Promise<Array<NFTMetadataLite>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPublicNFTs();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPublicNFTs();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPublicNFTsByOwner(arg0: Principal): Promise<Array<NFTMetadataLite>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPublicNFTsByOwner(arg0);
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPublicNFTsByOwner(arg0);
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPublicNFTsPaginated(arg0: bigint, arg1: bigint): Promise<NFTPageLite> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPublicNFTsPaginated(arg0, arg1);
                return from_candid_NFTPageLite_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPublicNFTsPaginated(arg0, arg1);
            return from_candid_NFTPageLite_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCmcDepositAddress(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getCmcDepositAddress();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCmcDepositAddress();
            return result;
        }
    }
    async getCollectionPhase(arg0: Principal): Promise<CollectionPhase> {
        if (this.processError) {
            try {
                const result = await this.actor.getCollectionPhase(arg0);
                return from_candid_CollectionPhase_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCollectionPhase(arg0);
            return from_candid_CollectionPhase_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCollectionStatus(arg0: Principal): Promise<{
        ownerPrincipal: Principal;
        imageCount: bigint;
        cycles: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getCollectionStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCollectionStatus(arg0);
            return result;
        }
    }
    async getFactoryAccountId(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getFactoryAccountId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFactoryAccountId();
            return result;
        }
    }
    async getICPPrice(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getICPPrice();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getICPPrice();
            return result;
        }
    }
    async getMyCollection(arg0: Principal): Promise<Principal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyCollection(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyCollection(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyCollectionCycles(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyCollectionCycles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyCollectionCycles();
            return result;
        }
    }
    async getMyHealthStatus(): Promise<HealthStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyHealthStatus();
                return from_candid_HealthStatus_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyHealthStatus();
            return from_candid_HealthStatus_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyMintCount(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyMintCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyMintCount(arg0);
            return result;
        }
    }
    async getMyNFTs(): Promise<Array<NFTMetadataLite>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyNFTs();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyNFTs();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyNFTsPaginated(arg0: bigint, arg1: bigint): Promise<NFTPageLite> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyNFTsPaginated(arg0, arg1);
                return from_candid_NFTPageLite_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyNFTsPaginated(arg0, arg1);
            return from_candid_NFTPageLite_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyPendingTransactions(): Promise<Array<PendingTx>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPendingTransactions();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPendingTransactions();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNFT(arg0: TokenId): Promise<NFTMetadata | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNFT(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNFT(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNFTHistory(arg0: TokenId): Promise<Array<TransactionEvent> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNFTHistory(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNFTHistory(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNFTImage(arg0: TokenId): Promise<Uint8Array | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNFTImage(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNFTImage(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingTransactions(): Promise<Array<PendingTx>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingTransactions();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingTransactions();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlatformFees(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlatformFees();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlatformFees();
            return result;
        }
    }
    async getStatus(): Promise<{
        memory: bigint;
        cycles: bigint;
        heap_memory: bigint;
        estimate_days: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStatus();
            return result;
        }
    }
    async getUserRegistryEntry(): Promise<Principal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserRegistryEntry();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserRegistryEntry();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async icrc10_supported_standards(): Promise<Array<Standard>> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc10_supported_standards();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc10_supported_standards();
            return result;
        }
    }
    async icrc7_description(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_description();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_description();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async icrc7_name(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_name();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_name();
            return result;
        }
    }
    async icrc7_owner_of(arg0: bigint): Promise<Account | null> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_owner_of(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_owner_of(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async icrc7_symbol(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_symbol();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_symbol();
            return result;
        }
    }
    async icrc7_token_metadata(arg0: Array<bigint>): Promise<Array<Array<[string, Value]> | null>> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_token_metadata(arg0);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_token_metadata(arg0);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async icrc7_tokens(arg0: bigint | null, arg1: bigint | null): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_tokens(to_candid_opt_n40(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n40(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_tokens(to_candid_opt_n40(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n40(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async icrc7_tokens_of(arg0: Account, arg1: bigint | null, arg2: bigint | null): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_tokens_of(to_candid_Account_n41(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n40(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n40(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_tokens_of(to_candid_Account_n41(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n40(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n40(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async icrc7_total_supply(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_total_supply();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_total_supply();
            return result;
        }
    }
    async initSelf(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initSelf();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initSelf();
            return result;
        }
    }
    async isUsingDefaultCollection(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isUsingDefaultCollection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isUsingDefaultCollection(arg0);
            return result;
        }
    }
    async listAdmins(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAdmins();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAdmins();
            return result;
        }
    }
    async mintNFT(arg0: string, arg1: string, arg2: Uint8Array, arg3: Principal | null, arg4: boolean, arg5: string | null): Promise<MintResult> {
        if (this.processError) {
            try {
                const result = await this.actor.mintNFT(arg0, arg1, arg2, to_candid_opt_n43(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n44(this._uploadFile, this._downloadFile, arg5));
                return from_candid_MintResult_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.mintNFT(arg0, arg1, arg2, to_candid_opt_n43(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n44(this._uploadFile, this._downloadFile, arg5));
            return from_candid_MintResult_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async processTopUp(arg0: bigint, arg1: Principal): Promise<ProcessTopUpResult> {
        if (this.processError) {
            try {
                const result = await this.actor.processTopUp(arg0, arg1);
                return from_candid_ProcessTopUpResult_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processTopUp(arg0, arg1);
            return from_candid_ProcessTopUpResult_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeAdmin(arg0: Principal): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAdmin(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAdmin(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async retryTopUp(arg0: bigint): Promise<ProcessTopUpResult> {
        if (this.processError) {
            try {
                const result = await this.actor.retryTopUp(arg0);
                return from_candid_ProcessTopUpResult_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.retryTopUp(arg0);
            return from_candid_ProcessTopUpResult_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async setNFTVisibility(arg0: TokenId, arg1: boolean): Promise<VisibilityResult> {
        if (this.processError) {
            try {
                const result = await this.actor.setNFTVisibility(arg0, arg1);
                return from_candid_VisibilityResult_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setNFTVisibility(arg0, arg1);
            return from_candid_VisibilityResult_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async topUpCollection(arg0: bigint): Promise<TopUpResult> {
        if (this.processError) {
            try {
                const result = await this.actor.topUpCollection(arg0);
                return from_candid_TopUpResult_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.topUpCollection(arg0);
            return from_candid_TopUpResult_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async transferNFT(arg0: TokenId, arg1: Principal): Promise<TransferResult> {
        if (this.processError) {
            try {
                const result = await this.actor.transferNFT(arg0, arg1);
                return from_candid_TransferResult_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transferNFT(arg0, arg1);
            return from_candid_TransferResult_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async withdrawPlatformFees(arg0: Principal): Promise<WithdrawResult> {
        if (this.processError) {
            try {
                const result = await this.actor.withdrawPlatformFees(arg0);
                return from_candid_WithdrawResult_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.withdrawPlatformFees(arg0);
            return from_candid_WithdrawResult_n50(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Account_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Account): Account {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_CollectionPhase_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CollectionPhase): CollectionPhase {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_CycleHealth_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CycleHealth): CycleHealth {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_HealthStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HealthStatus): HealthStatus {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_MintResult_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MintResult): MintResult {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_NFTMetadataLite_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NFTMetadataLite): NFTMetadataLite {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_NFTMetadata_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NFTMetadata): NFTMetadata {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_NFTPageLite_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NFTPageLite): NFTPageLite {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_PendingTx_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PendingTx): PendingTx {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_ProcessTopUpResult_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProcessTopUpResult): ProcessTopUpResult {
    return from_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function from_candid_TopUpResult_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TopUpResult): TopUpResult {
    return from_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionEvent_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionEvent): TransactionEvent {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_TransferResult_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransferResult): TransferResult {
    return from_candid_variant_n1(_uploadFile, _downloadFile, value);
}
function from_candid_TxStatus_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TxStatus): TxStatus {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Value_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_VisibilityResult_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VisibilityResult): VisibilityResult {
    return from_candid_variant_n1(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawResult_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawResult): WithdrawResult {
    return from_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NFTMetadata]): NFTMetadata | null {
    return value.length === 0 ? null : from_candid_NFTMetadata_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_TransactionEvent>]): Array<TransactionEvent> | null {
    return value.length === 0 ? null : from_candid_vec_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Account]): Account | null {
    return value.length === 0 ? null : from_candid_Account_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<[string, _Value]>]): Array<[string, Value]> | null {
    return value.length === 0 ? null : from_candid_vec_n36(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    items: Array<_NFTMetadataLite>;
}): {
    total: bigint;
    items: Array<NFTMetadataLite>;
} {
    return {
        total: value.total,
        items: from_candid_vec_n4(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    daysPercentage: bigint;
    imagesRemaining: bigint;
    estimatedStorageMB: bigint;
    healthColor: _CycleHealth;
    rawCycles: bigint;
    daysRemaining: bigint;
}): {
    status: string;
    daysPercentage: bigint;
    imagesRemaining: bigint;
    estimatedStorageMB: bigint;
    healthColor: CycleHealth;
    rawCycles: bigint;
    daysRemaining: bigint;
} {
    return {
        status: value.status,
        daysPercentage: value.daysPercentage,
        imagesRemaining: value.imagesRemaining,
        estimatedStorageMB: value.estimatedStorageMB,
        healthColor: from_candid_CycleHealth_n19(_uploadFile, _downloadFile, value.healthColor),
        rawCycles: value.rawCycles,
        daysRemaining: value.daysRemaining
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _TxStatus;
    lastAttemptAt: bigint;
    collectionId: Principal;
    createdAt: bigint;
    retryCount: bigint;
    blockIndex: bigint;
    caller: Principal;
    amount: bigint;
}): {
    status: TxStatus;
    lastAttemptAt: bigint;
    collectionId: Principal;
    createdAt: bigint;
    retryCount: bigint;
    blockIndex: bigint;
    caller: Principal;
    amount: bigint;
} {
    return {
        status: from_candid_TxStatus_n24(_uploadFile, _downloadFile, value.status),
        lastAttemptAt: value.lastAttemptAt,
        collectionId: value.collectionId,
        createdAt: value.createdAt,
        retryCount: value.retryCount,
        blockIndex: value.blockIndex,
        caller: value.caller,
        amount: value.amount
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tokenId: _TokenId;
    owner: Principal;
    name: string;
    createdAt: _Time;
    description: string;
    history: Array<_TransactionEvent>;
    image: Uint8Array;
    isPublic: boolean;
    collectionName: [] | [string];
}): {
    tokenId: TokenId;
    owner: Principal;
    name: string;
    createdAt: Time;
    description: string;
    history: Array<TransactionEvent>;
    image: Uint8Array;
    isPublic: boolean;
    collectionName?: string;
} {
    return {
        tokenId: value.tokenId,
        owner: value.owner,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        history: from_candid_vec_n7(_uploadFile, _downloadFile, value.history),
        image: value.image,
        isPublic: value.isPublic,
        collectionName: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.collectionName))
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    owner: Principal;
    subaccount: [] | [Uint8Array];
}): {
    owner: Principal;
    subaccount?: Uint8Array;
} {
    return {
        owner: value.owner,
        subaccount: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.subaccount))
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tokenId: _TokenId;
    owner: Principal;
    name: string;
    createdAt: _Time;
    description: string;
    history: Array<_TransactionEvent>;
    isPublic: boolean;
    collectionName: [] | [string];
}): {
    tokenId: TokenId;
    owner: Principal;
    name: string;
    createdAt: Time;
    description: string;
    history: Array<TransactionEvent>;
    isPublic: boolean;
    collectionName?: string;
} {
    return {
        tokenId: value.tokenId,
        owner: value.owner,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        history: from_candid_vec_n7(_uploadFile, _downloadFile, value.history),
        isPublic: value.isPublic,
        collectionName: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.collectionName))
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    to: Principal;
    from: [] | [Principal];
    timestamp: bigint;
    eventType: {
        Mint: null;
    } | {
        Transfer: null;
    };
}): {
    to: Principal;
    from?: Principal;
    timestamp: bigint;
    eventType: Variant_Mint_Transfer;
} {
    return {
        to: value.to,
        from: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.from)),
        timestamp: value.timestamp,
        eventType: from_candid_variant_n11(_uploadFile, _downloadFile, value.eventType)
    };
}
function from_candid_tuple_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _Value]): [string, Value] {
    return [
        value[0],
        from_candid_Value_n38(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Mint: null;
} | {
    Transfer: null;
}): Variant_Mint_Transfer {
    return "Mint" in value ? Variant_Mint_Transfer.Mint : "Transfer" in value ? Variant_Mint_Transfer.Transfer : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Premium: null;
} | {
    Free: null;
} | {
    Bonus: null;
}): CollectionPhase {
    return "Premium" in value ? CollectionPhase.Premium : "Free" in value ? CollectionPhase.Free : "Bonus" in value ? CollectionPhase.Bonus : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    red: null;
} | {
    orange: null;
} | {
    green: null;
}): CycleHealth {
    return "red" in value ? CycleHealth.red : "orange" in value ? CycleHealth.orange : "green" in value ? CycleHealth.green : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    failed: null;
}): TxStatus {
    return "pending" in value ? TxStatus.pending : "completed" in value ? TxStatus.completed : "failed" in value ? TxStatus.failed : value;
}
function from_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        platformFee: bigint;
        icpUsed: bigint;
        cyclesMinted: bigint;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        platformFee: bigint;
        icpUsed: bigint;
        cyclesMinted: bigint;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Int: bigint;
} | {
    Map: Array<[string, _Value]>;
} | {
    Nat: bigint;
} | {
    Blob: Uint8Array;
} | {
    Bool: boolean;
} | {
    Text: string;
} | {
    Array: Array<[string, _Value]>;
}): {
    __kind__: "Int";
    Int: bigint;
} | {
    __kind__: "Map";
    Map: Array<[string, Value]>;
} | {
    __kind__: "Nat";
    Nat: bigint;
} | {
    __kind__: "Blob";
    Blob: Uint8Array;
} | {
    __kind__: "Bool";
    Bool: boolean;
} | {
    __kind__: "Text";
    Text: string;
} | {
    __kind__: "Array";
    Array: Array<[string, Value]>;
} {
    return "Int" in value ? {
        __kind__: "Int",
        Int: value.Int
    } : "Map" in value ? {
        __kind__: "Map",
        Map: from_candid_vec_n36(_uploadFile, _downloadFile, value.Map)
    } : "Nat" in value ? {
        __kind__: "Nat",
        Nat: value.Nat
    } : "Blob" in value ? {
        __kind__: "Blob",
        Blob: value.Blob
    } : "Bool" in value ? {
        __kind__: "Bool",
        Bool: value.Bool
    } : "Text" in value ? {
        __kind__: "Text",
        Text: value.Text
    } : "Array" in value ? {
        __kind__: "Array",
        Array: from_candid_vec_n36(_uploadFile, _downloadFile, value.Array)
    } : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _TokenId;
} | {
    err: string;
} | {
    paymentRequired: null;
}): {
    __kind__: "ok";
    ok: TokenId;
} | {
    __kind__: "err";
    err: string;
} | {
    __kind__: "paymentRequired";
    paymentRequired: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : "paymentRequired" in value ? {
        __kind__: "paymentRequired",
        paymentRequired: value.paymentRequired
    } : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PendingTx>): Array<PendingTx> {
    return value.map((x)=>from_candid_PendingTx_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[] | [Array<[string, _Value]>]>): Array<Array<[string, Value]> | null> {
    return value.map((x)=>from_candid_opt_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _Value]>): Array<[string, Value]> {
    return value.map((x)=>from_candid_tuple_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NFTMetadataLite>): Array<NFTMetadataLite> {
    return value.map((x)=>from_candid_NFTMetadataLite_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TransactionEvent>): Array<TransactionEvent> {
    return value.map((x)=>from_candid_TransactionEvent_n8(_uploadFile, _downloadFile, x));
}
function to_candid_Account_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Account): _Account {
    return to_candid_record_n42(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [Principal] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    owner: Principal;
    subaccount?: Uint8Array;
}): {
    owner: Principal;
    subaccount: [] | [Uint8Array];
} {
    return {
        owner: value.owner,
        subaccount: value.subaccount ? candid_some(value.subaccount) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
