/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface NFTPage {
    total: bigint;
    items: Array<NFTMetadata>;
}
export interface Account {
    owner: Principal;
    subaccount?: Uint8Array;
}
export type Time = bigint;
export type TransferResult = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export type TokenId = bigint;
export interface TransactionEvent {
    to: Principal;
    from?: Principal;
    timestamp: bigint;
    eventType: Variant_Mint_Transfer;
}
export type MintResult = {
    __kind__: "ok";
    ok: TokenId;
} | {
    __kind__: "err";
    err: string;
} | {
    __kind__: "paymentRequired";
    paymentRequired: null;
};
export interface NFTMetadata {
    tokenId: TokenId;
    owner: Principal;
    name: string;
    createdAt: Time;
    description: string;
    history: Array<TransactionEvent>;
    image: Uint8Array;
    isPublic: boolean;
}
export type VisibilityResult = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export type Value = {
    __kind__: "Int";
    Int: bigint;
} | {
    __kind__: "Map";
    Map: Array<[string, Value]>;
} | {
    __kind__: "Nat";
    Nat: bigint;
} | {
    __kind__: "Blob";
    Blob: Uint8Array;
} | {
    __kind__: "Bool";
    Bool: boolean;
} | {
    __kind__: "Text";
    Text: string;
} | {
    __kind__: "Array";
    Array: Array<[string, Value]>;
};
export interface Standard {
    url: string;
    name: string;
}
export enum CollectionPhase {
    premium = "premium",
    free = "free",
    bonus = "bonus"
}
export enum Variant_Mint_Transfer {
    Mint = "Mint",
    Transfer = "Transfer"
}
export interface backendInterface {
    createMyCollection(): Promise<string>;
    getAllPublicNFTs(): Promise<Array<NFTMetadata>>;
    getAllPublicNFTsPaginated(offset: bigint, limit: bigint): Promise<NFTPage>;
    getCollectionPhase(user: Principal): Promise<CollectionPhase>;
    getMyCollection(user: Principal): Promise<Principal | null>;
    getMyMintCount(user: Principal): Promise<bigint>;
    getMyNFTs(): Promise<Array<NFTMetadata>>;
    getMyNFTsPaginated(offset: bigint, limit: bigint): Promise<NFTPage>;
    getNFT(tokenId: TokenId): Promise<NFTMetadata | null>;
    getNFTHistory(tokenId: TokenId): Promise<Array<TransactionEvent> | null>;
    icrc10_supported_standards(): Promise<Array<Standard>>;
    icrc7_description(): Promise<string | null>;
    icrc7_name(): Promise<string>;
    icrc7_owner_of(tokenId: bigint): Promise<Account | null>;
    icrc7_symbol(): Promise<string>;
    icrc7_token_metadata(tokenIds: Array<bigint>): Promise<Array<Array<[string, Value]> | null>>;
    icrc7_tokens(prev: bigint | null, take: bigint | null): Promise<Array<bigint>>;
    icrc7_tokens_of(account: Account, prev: bigint | null, take: bigint | null): Promise<Array<bigint>>;
    icrc7_total_supply(): Promise<bigint>;
    mintNFT(name: string, description: string, image: Uint8Array, recipientOpt: Principal | null, isPublic: boolean): Promise<MintResult>;
    setNFTVisibility(tokenId: TokenId, isPublic: boolean): Promise<VisibilityResult>;
    transferNFT(tokenId: TokenId, to: Principal): Promise<TransferResult>;
}
import type { Account as _Account, CollectionPhase as _CollectionPhase, MintResult as _MintResult, NFTMetadata as _NFTMetadata, NFTPage as _NFTPage, Time as _Time, TokenId as _TokenId, TransactionEvent as _TransactionEvent, TransferResult as _TransferResult, Value as _Value, VisibilityResult as _VisibilityResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createMyCollection(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createMyCollection();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMyCollection();
            return result;
        }
    }
    async getAllPublicNFTs(): Promise<Array<NFTMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPublicNFTs();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPublicNFTs();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPublicNFTsPaginated(arg0: bigint, arg1: bigint): Promise<NFTPage> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPublicNFTsPaginated(arg0, arg1);
                return from_candid_NFTPage_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPublicNFTsPaginated(arg0, arg1);
            return from_candid_NFTPage_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCollectionPhase(arg0: Principal): Promise<CollectionPhase> {
        if (this.processError) {
            try {
                const result = await this.actor.getCollectionPhase(arg0);
                return from_candid_CollectionPhase_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCollectionPhase(arg0);
            return from_candid_CollectionPhase_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyCollection(arg0: Principal): Promise<Principal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyCollection(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyCollection(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyMintCount(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyMintCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyMintCount(arg0);
            return result;
        }
    }
    async getMyNFTs(): Promise<Array<NFTMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyNFTs();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyNFTs();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyNFTsPaginated(arg0: bigint, arg1: bigint): Promise<NFTPage> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyNFTsPaginated(arg0, arg1);
                return from_candid_NFTPage_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyNFTsPaginated(arg0, arg1);
            return from_candid_NFTPage_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNFT(arg0: TokenId): Promise<NFTMetadata | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNFT(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNFT(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNFTHistory(arg0: TokenId): Promise<Array<TransactionEvent> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNFTHistory(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNFTHistory(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async icrc10_supported_standards(): Promise<Array<Standard>> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc10_supported_standards();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc10_supported_standards();
            return result;
        }
    }
    async icrc7_description(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_description();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_description();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async icrc7_name(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_name();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_name();
            return result;
        }
    }
    async icrc7_owner_of(arg0: bigint): Promise<Account | null> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_owner_of(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_owner_of(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async icrc7_symbol(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_symbol();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_symbol();
            return result;
        }
    }
    async icrc7_token_metadata(arg0: Array<bigint>): Promise<Array<Array<[string, Value]> | null>> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_token_metadata(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_token_metadata(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async icrc7_tokens(arg0: bigint | null, arg1: bigint | null): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_tokens(to_candid_opt_n26(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_tokens(to_candid_opt_n26(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async icrc7_tokens_of(arg0: Account, arg1: bigint | null, arg2: bigint | null): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_tokens_of(to_candid_Account_n27(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_tokens_of(to_candid_Account_n27(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n26(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async icrc7_total_supply(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.icrc7_total_supply();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.icrc7_total_supply();
            return result;
        }
    }
    async mintNFT(arg0: string, arg1: string, arg2: Uint8Array, arg3: Principal | null, arg4: boolean): Promise<MintResult> {
        if (this.processError) {
            try {
                const result = await this.actor.mintNFT(arg0, arg1, arg2, to_candid_opt_n29(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_MintResult_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.mintNFT(arg0, arg1, arg2, to_candid_opt_n29(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_MintResult_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async setNFTVisibility(arg0: TokenId, arg1: boolean): Promise<VisibilityResult> {
        if (this.processError) {
            try {
                const result = await this.actor.setNFTVisibility(arg0, arg1);
                return from_candid_VisibilityResult_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setNFTVisibility(arg0, arg1);
            return from_candid_VisibilityResult_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async transferNFT(arg0: TokenId, arg1: Principal): Promise<TransferResult> {
        if (this.processError) {
            try {
                const result = await this.actor.transferNFT(arg0, arg1);
                return from_candid_TransferResult_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transferNFT(arg0, arg1);
            return from_candid_TransferResult_n34(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Account_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Account): Account {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_CollectionPhase_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CollectionPhase): CollectionPhase {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_MintResult_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MintResult): MintResult {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_NFTMetadata_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NFTMetadata): NFTMetadata {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_NFTPage_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NFTPage): NFTPage {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionEvent_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionEvent): TransactionEvent {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_TransferResult_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransferResult): TransferResult {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_Value_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_VisibilityResult_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VisibilityResult): VisibilityResult {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NFTMetadata]): NFTMetadata | null {
    return value.length === 0 ? null : from_candid_NFTMetadata_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_TransactionEvent>]): Array<TransactionEvent> | null {
    return value.length === 0 ? null : from_candid_vec_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Account]): Account | null {
    return value.length === 0 ? null : from_candid_Account_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<[string, _Value]>]): Array<[string, Value]> | null {
    return value.length === 0 ? null : from_candid_vec_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    items: Array<_NFTMetadata>;
}): {
    total: bigint;
    items: Array<NFTMetadata>;
} {
    return {
        total: value.total,
        items: from_candid_vec_n1(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    owner: Principal;
    subaccount: [] | [Uint8Array];
}): {
    owner: Principal;
    subaccount?: Uint8Array;
} {
    return {
        owner: value.owner,
        subaccount: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.subaccount))
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tokenId: _TokenId;
    owner: Principal;
    name: string;
    createdAt: _Time;
    description: string;
    history: Array<_TransactionEvent>;
    image: Uint8Array;
    isPublic: boolean;
}): {
    tokenId: TokenId;
    owner: Principal;
    name: string;
    createdAt: Time;
    description: string;
    history: Array<TransactionEvent>;
    image: Uint8Array;
    isPublic: boolean;
} {
    return {
        tokenId: value.tokenId,
        owner: value.owner,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        history: from_candid_vec_n4(_uploadFile, _downloadFile, value.history),
        image: value.image,
        isPublic: value.isPublic
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    to: Principal;
    from: [] | [Principal];
    timestamp: bigint;
    eventType: {
        Mint: null;
    } | {
        Transfer: null;
    };
}): {
    to: Principal;
    from?: Principal;
    timestamp: bigint;
    eventType: Variant_Mint_Transfer;
} {
    return {
        to: value.to,
        from: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.from)),
        timestamp: value.timestamp,
        eventType: from_candid_variant_n8(_uploadFile, _downloadFile, value.eventType)
    };
}
function from_candid_tuple_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, _Value]): [string, Value] {
    return [
        value[0],
        from_candid_Value_n24(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    premium: null;
} | {
    free: null;
} | {
    bonus: null;
}): CollectionPhase {
    return "premium" in value ? CollectionPhase.premium : "free" in value ? CollectionPhase.free : "bonus" in value ? CollectionPhase.bonus : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Int: bigint;
} | {
    Map: Array<[string, _Value]>;
} | {
    Nat: bigint;
} | {
    Blob: Uint8Array;
} | {
    Bool: boolean;
} | {
    Text: string;
} | {
    Array: Array<[string, _Value]>;
}): {
    __kind__: "Int";
    Int: bigint;
} | {
    __kind__: "Map";
    Map: Array<[string, Value]>;
} | {
    __kind__: "Nat";
    Nat: bigint;
} | {
    __kind__: "Blob";
    Blob: Uint8Array;
} | {
    __kind__: "Bool";
    Bool: boolean;
} | {
    __kind__: "Text";
    Text: string;
} | {
    __kind__: "Array";
    Array: Array<[string, Value]>;
} {
    return "Int" in value ? {
        __kind__: "Int",
        Int: value.Int
    } : "Map" in value ? {
        __kind__: "Map",
        Map: from_candid_vec_n22(_uploadFile, _downloadFile, value.Map)
    } : "Nat" in value ? {
        __kind__: "Nat",
        Nat: value.Nat
    } : "Blob" in value ? {
        __kind__: "Blob",
        Blob: value.Blob
    } : "Bool" in value ? {
        __kind__: "Bool",
        Bool: value.Bool
    } : "Text" in value ? {
        __kind__: "Text",
        Text: value.Text
    } : "Array" in value ? {
        __kind__: "Array",
        Array: from_candid_vec_n22(_uploadFile, _downloadFile, value.Array)
    } : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _TokenId;
} | {
    err: string;
} | {
    paymentRequired: null;
}): {
    __kind__: "ok";
    ok: TokenId;
} | {
    __kind__: "err";
    err: string;
} | {
    __kind__: "paymentRequired";
    paymentRequired: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : "paymentRequired" in value ? {
        __kind__: "paymentRequired",
        paymentRequired: value.paymentRequired
    } : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Mint: null;
} | {
    Transfer: null;
}): Variant_Mint_Transfer {
    return "Mint" in value ? Variant_Mint_Transfer.Mint : "Transfer" in value ? Variant_Mint_Transfer.Transfer : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NFTMetadata>): Array<NFTMetadata> {
    return value.map((x)=>from_candid_NFTMetadata_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[] | [Array<[string, _Value]>]>): Array<Array<[string, Value]> | null> {
    return value.map((x)=>from_candid_opt_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, _Value]>): Array<[string, Value]> {
    return value.map((x)=>from_candid_tuple_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TransactionEvent>): Array<TransactionEvent> {
    return value.map((x)=>from_candid_TransactionEvent_n5(_uploadFile, _downloadFile, x));
}
function to_candid_Account_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Account): _Account {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [Principal] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    owner: Principal;
    subaccount?: Uint8Array;
}): {
    owner: Principal;
    subaccount: [] | [Uint8Array];
} {
    return {
        owner: value.owner,
        subaccount: value.subaccount ? candid_some(value.subaccount) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
